CREATE TABLE player (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    passphrase text,
    origin_player_id bigint
);

CREATE TABLE game (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rows_val int NOT NULL,
    cols_val int NOT NULL
);

CREATE TABLE player_move (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn int NOT NULL,
    row_val int NOT NULL,
    col_val int NOT NULL,
    player_id bigint,
    game_id bigint NOT NULL
);

CREATE TABLE ship (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_start int NOT NULL,
    row_end int NOT NULL,
    col_start int NOT NULL,
    col_end int NOT NULL,
    player_id bigint,
    game_id bigint NOT NULL
);

ALTER TABLE player
    ADD CONSTRAINT fk_origin_player_id FOREIGN KEY (origin_player_id) REFERENCES player (id) ON DELETE SET NULL;

ALTER TABLE player_move
    ADD CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL;

ALTER TABLE player_move
    ADD CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE;

ALTER TABLE ship
    ADD CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL;

ALTER TABLE ship
    ADD CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE;
