CREATE TABLE player (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(50) UNIQUE
);

-- might not be necessary
CREATE TABLE player_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  wins INTEGER NOT NULL,
  loses INTEGER NOT NULL
)

CREATE TABLE game (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      
);

ALTER TABLE player_stats
ADD COLUMN player_id INTEGER;

ALTER TABLE player_stats add CONSTRAINT fk_player_id FOREIGN key (player_id) REFERENCES player (id);

